# Generated by Django 5.2.4 on 2025-07-22 08:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='app.lecture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='app.group'),
        ),
    ]
