# Generated by Django 5.2.4 on 2025-07-22 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_schedule_class_room_schedule_lecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='subject_type',
            field=models.CharField(choices=[('1', 'solo'), ('2', 'double')], default=1, max_length=1),
        ),
    ]
