# Generated by Django 5.2.4 on 2025-07-22 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_lecture_title_lecture_video_schedule_class_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Src',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('url', models.URLField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srcs', to='app.lecture')),
            ],
        ),
    ]
