# Generated by Django 5.2.4 on 2025-07-23 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_schedule_class_room_src'),
    ]

    
