# Generated by Django 5.2.4 on 2025-07-24 07:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_schedule_class_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('time', models.URLField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timepoints', to='app.lecture')),
            ],
        ),
        migrations.DeleteModel(
            name='Src',
        ),
    ]
