# Generated by Django 5.2.4 on 2025-07-24 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_schedule_class_room_timepoint_delete_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='class_room',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timepoint',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timepoint',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
