# Generated by Django 5.2.4 on 2025-07-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_lecture_options_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='subject_type',
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_double',
            field=models.BooleanField(default=False),
        ),
    ]
