# Generated by Django 5.2.4 on 2025-07-26 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_schedule_subject_type_schedule_is_double'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='day',
            new_name='dayOfWeek',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='dateOfDay',
            field=models.CharField(default=datetime.datetime(2025, 7, 26, 8, 24, 43, 225169, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='dateOfWeek',
            field=models.CharField(default=datetime.datetime(2025, 7, 26, 8, 24, 51, 229198, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
