# Generated by Django 5.2.4 on 2025-07-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_day_schedule_dayofweek_remove_schedule_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='dateOfWeek',
        ),
    ]
