# Generated by Django 5.2.4 on 2025-07-26 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_schedule_dateofweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='dateOfWeek',
            field=models.CharField(default=datetime.datetime(2025, 7, 26, 8, 45, 15, 690751, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
