# Generated by Django 5.2.4 on 2025-07-26 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_user_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='class_room',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='subject',
            name='class_room',
            field=models.CharField(default=datetime.datetime(2025, 7, 26, 12, 5, 39, 477026, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
