# Generated by Django 5.2.4 on 2025-07-26 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_schedule_class_room_remove_schedule_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='dateOfDay',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='dateOfWeek',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='dayOfWeek',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 7, 26, 12, 10, 38, 849555, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
