# Generated by Django 5.2.4 on 2025-07-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_schedule_dateofday_remove_schedule_dateofweek_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='subject',
        ),
    ]
